name: "build on push"

on: [push]

jobs:
  build:
    name: "project building and validation"
    runs-on: ubuntu-latest
    steps:
      - name: "project building and validation"
        run: mvn verify