name: "build on push"

on: [push]

jobs:
  build:
    name: "project building and validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "maven with verify goal"
        run: mvn verify