name: "build on push"

on: [push]

jobs:
  build:
    name: "project building and validation"
    runs-on: "ubuntu-latest"
    steps:

      - name: "checkout project"
        uses: "actions/checkout@v2"

      - name: "setup Java 16"
        uses: "actions/setup-java@v2"
        with:
          distribution: "zulu"
          java-version: "16"

      - name: "build and verify"
        run: "mvn verify --no-transfer-progress --errors"

      - name: "generate JaCoCo badge"
        uses: "cicirello/jacoco-badge-generator@v2"